"""Añadir tabla de usuarios

Revision ID: 35879864b73c
Revises: b30e86bafc8d
Create Date: 2025-07-19 05:23:58.758056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35879864b73c'
down_revision = 'b30e86bafc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
