"""Añadir user_id a la tabla Task

Revision ID: 5a7a3d2bb8b8
Revises: 35879864b73c
Create Date: 2025-07-19 07:31:39.776612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7a3d2bb8b8'
down_revision = '35879864b73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Paso 1: Añadimos la columna, permitiendo que esté vacía temporalmente.
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Paso 2: Actualizamos todas las tareas existentes para que pertenezcan al usuario con ID 1.
    op.execute('UPDATE task SET user_id = 1')
    
    # Paso 3: Ahora sí, hacemos que la columna sea obligatoria para el futuro.
    op.alter_column('task', 'user_id', nullable=False)
    
    # Creamos la relación de clave foránea
    op.create_foreign_key('fk_task_user_id', 'task', 'user', ['user_id'], ['id'])
    
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
